services:
  server:
    image: "ruby:2.7"
    volumes:
      - ./hackers-revenge-server/:/app
      - ./hackers-revenge-server/db:/app/db:rw
      - ./hackers-revenge-server/vendor:/usr/local/bundle
    working_dir: /app
    command: ["sh", "run.sh"]
  redis:
    image: "redis:alpine"
  ui:
    image: "nginx:latest"
    volumes:
      - ./hackers-revenge-ui/docs:/usr/share/nginx/html
      - ./hackers-revenge-ui/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./hackers-revenge-ui/auth.conf:/etc/nginx/auth.conf
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: "80"
      SERVER_HOST: "http://server:3000"
