name: hackers-revenge
services:
  server:
    environment:
      RAILS_ENV: development
      MAX_PROGRAMS_PER_PLAYER: 12
      TOURNAMENT_END_TIME: "2024-11-16 07:59:59"
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
    image: "ruby:3.3"
    volumes:
      - ./hackers-revenge-server/:/app
      - ./hackers-revenge-server/vendor:/usr/local/bundle
    working_dir: /app
    command: sh run.sh
    healthcheck:
      test: curl -f http://server:3000/healthy
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 2s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: "redis:alpine"
    healthcheck:
      test: redis-cli ping | grep PONG
      start_period: 15s
      interval: 10s
      timeout: 1s
      retries: 3
    restart: on-failure
  ui:
    image: "nginx:latest"
    volumes:
      - ./hackers-revenge-ui/docs:/usr/share/nginx/html:ro
      - ./hackers-revenge-ui/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./htpasswd:/usr/share/nginx/htpasswd:ro
      - ./certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: "hcf.xyloguy.org"
      SERVER_HOST: "http://server:3000"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: curl -f http://ui:80/healthy
      start_period: 15s
      interval: 10s
      retries: 3
      timeout: 2s
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  mysql_data: