source "https://rubygems.org"

# Rails
gem "rails", ">= 7.2.1"
gem "ostruct"
gem "mysql2"

# Use Puma as the app server
gem "puma", "~> 6.4"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.18.4", :require => false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# Use faker for random words and stuff
gem "faker"

# Use sidekiq for deferred processing
gem 'sidekiq', '~> 7.3', '>= 7.3.2'

group :development, :test do
  # Test with RSpec and FactoryBot
  gem "factory_bot_rails"
  gem "rspec-rails"

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", :platforms => [:mri, :mingw, :x64_mingw]
  gem "pry-byebug"

  # Linter
  gem "rubocop", :require => false
  gem "rubocop-performance", :require => false
  gem "rubocop-rails", :require => false
end

group :development do
  gem "listen", ">= 3.5"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", :platforms => [:mingw, :mswin, :x64_mingw, :jruby]
